[aliases]
test = pytest

[build_sphinx]
source-dir = docs/
build-dir = docs/_build
all_files = 1

[bdist_wheel]
universal = 1

[pydocstyle]
add_ignore = D401

[metadata]
version = 1.2.8+lineaje.1
maintainer = Lineaje DepFixer
maintainer_email = 221268890+Lineaje-DepFixer@users.noreply.github.com
url = https://github.com/lineaje-labs-gos/inveniosoftware-invenio-rest
project_urls = Homepage = https://github.com/lineaje-labs-gos/inveniosoftware-invenio-rest
	Repository = https://github.com/lineaje-labs-gos/inveniosoftware-invenio-rest
	Tracker = https://github.com/lineaje-labs-gos/inveniosoftware-invenio-rest/issues

